package com.orderbook.engine.strategy;

import com.orderbook.engine.model.Order;
import com.orderbook.engine.model.Trade;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

/**
 * Contract shared by every order book implementation (linked list, BST, TreeMap,
 * priority queue, ...) so they can be swapped and benchmarked against each other
 * without the caller knowing which data structure backs them.
 *
 * All implementations enforce price-time priority: among orders at the same
 * price, the one with the earlier timestamp fills first.
 */
public interface OrderBook {

    /**
     * Adds a new order to the book. If it crosses the opposite side, it is
     * matched immediately (possibly partially); any unfilled remainder rests
     * in the book. Returns the trades generated by this call, in execution order.
     */
    List<Trade> addOrder(Order order);

    /**
     * Removes a resting order from the book by id. Returns false if no active
     * order with that id was found (already filled, cancelled, or unknown).
     */
    boolean cancelOrder(String orderId);

    /**
     * Runs matching passes while the book is crossed (best bid >= best ask),
     * generating trades at the resting order's price. Called internally by
     * addOrder, but also exposed so callers/benchmarks can trigger it directly.
     */
    List<Trade> matchOrders();

    /** Highest resting buy price, if any. */
    Optional<BigDecimal> getBestBid();

    /** Lowest resting sell price, if any. */
    Optional<BigDecimal> getBestAsk();
}
